// Cloudflare Worker for the e2job site. wrangler.jsonc runs it first only for
// /sitemap.xml, which is generated by the API; every other request is served
// from the built static assets (with the single-page-app fallback).

const SITEMAP_URL = "https://api.e2job.com/sitemap.xml";

const proxySitemap = async () => {
  let upstream;
  try {
    upstream = await fetch(SITEMAP_URL, { headers: { Accept: "application/xml" } });
  } catch {
    return new Response("Sitemap is temporarily unavailable.", { status: 502 });
  }
  // A failing API is reported as a bad gateway, and not cached for an hour.
  if (upstream.status >= 500) {
    return new Response("Sitemap is temporarily unavailable.", { status: 502 });
  }
  return new Response(upstream.body, {
    status: upstream.status,
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
};

export default {
  async fetch(request, env) {
    const { pathname } = new URL(request.url);
    if (request.method === "GET" && pathname === "/sitemap.xml") return proxySitemap();
    return env.ASSETS.fetch(request);
  },
};
